export const SHOW_ALERT = "alert/SHOW_ALERT"
export const HIDE_ALERT = "alert/HIDE_ALERT"
export const GET_USERS = "GH/GET_USERS"
export const CLEAR_USERS = "GH/CLEAR_USERS"
export const GET_REPOS = "GH/GET_REPOS"
export const SEARCH_USERS = "GH/SEARCH_USERS"
export const SET_LOADING = "GH/SET_LOADING"